controllers:
    resource: ../src/Controller/
    type: attribute
app_booking_new:
    path: /booking/new
    controller: App\Controller\BookingNewController::newBooking
    methods: [GET, POST]  # Assurez-vous d'autoriser les méthodes GET et POST si vous utilisez un formulaire pour créer de nouvelles réservations
